app:
  name: 'users-service-mail'
  host: 'http://localhost'
  port: 5000

db:
  redis:
    port: 6379
    host: 'localhost'
    password:

sendinblue:
  url: 'https://api.sendinblue.com/v3'
  api_key: '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'
  name: 'ePayco'
  email_from: 'example@epayco.com'
